### ISSUE TITLE
App Transport on PFFile with Swift2

### ISSUE THREAD

**Issue by Jeffchiucp** [Jeffchiucp/Parse_WallPosts#12]
Using Xcode Version 9.0.1 (7A1001)
Parse Version: Latest

Error message that print out from the 
There are some error with the App Transport Security policy requires the use of a secure connection.

Error log generated from CompleteBlock for Parse(s)PFImageView(im)loadInBackground:progressBlock:
Optional(Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." 

UserInfo={NSUnderlyingError=0x7fabe8c4e570 {Error Domain=kCFErrorDomainCFNetwork Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSErrorFailingURLStringKey=http://files.parsetfss.com/154b660f-a7bc-440c-9815-aa76b93d70e3/tfss-08c21257-9a0a-44b8-89f9-e1d007c94fb3-image, NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLKey=http://files.parsetfss.com/154b660f-a7bc-440c-9815-aa76b93d70e3/tfss-08c21257-9a0a-44b8-89f9-e1d007c94fb3-image}}, NSErrorFailingURLStringKey=http://files.parsetfss.com/154b660f-a7bc-440c-9815-aa76b93d70e3/tfss-08c21257-9a0a-44b8-89f9-e1d007c94fb3-image, NSErrorFailingURLKey=http://files.parsetfss.com/154b660f-a7bc-440c-9815-aa76b93d70e3/tfss-08c21257-9a0a-44b8-89f9-e1d007c94fb3-image, NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.})

This is super strange, since we fully comply with App Transport Security on PFFiles on SDKs starting

**Comment by Jeffchiucp** [comment]
<img width="1175" alt="screen shot 2016-02-08 at 3 27 30 pm" src="https://cloud.githubusercontent.com/assets/10523517/12902854/89cf4e84-ce78-11e5-9c3d-8851c1854628.png">

Screen shot of the issue

**Comment by Jeffchiucp** [comment]
Apple now has official documentation for App Transport Security.

With iOS 9 and OS X El Capitan, Apple has introduced App Transport Security. In a nutshell, App Transport Security enforces best practices for secure network connections — notably, TLS 1.2 and forward secrecy. In the future, Apple will also update these best practices to ensure they always reflect the latest security practices that will keep network data secure.

WORKING WITH APPLE’S APP TRANSPORT SECURITY

http://www.neglectedpotential.com/2015/06/working-with-apples-application-transport-security/

**Comment by Jeffchiucp** [comment]
Updated solution. Udacity has an useful video for Network Security and APP TRANSPORT SECURITY. https://www.udacity.com/course/viewer#!/c-ud421-nd/l-6832698551/m-6559368973

**Comment by Jeffchiucp** [comment]
Added WORKING WITH APPLE’S APP TRANSPORT SECURITY. 
<img width="1009" alt="screen shot 2016-02-13 at 8 46 17 am" src="https://cloud.githubusercontent.com/assets/10523517/13028797/6d1d6bb8-d22e-11e5-9530-b10d2644f0d4.png">
Now you can see all the pictures.

**Comment by uttamraj143** [comment]
I am getting error while fetch images from parse I am getting this error "NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=http://files.parsetfss.com/babb57f8-11ac-4ae7-b1a9-ec2f3de4dbf6/tfss-8a4b256b-78ad-499b-af25-698866238e4a-stmaryangels.jpg" Can any one help me on this...
